# ArXiv Query Configuration for Multi-Agent Papers
# Configuration to retrieve recent papers on multi-agent systems in computer science

# General search keywords
keywords:
  - "multi-agent"
  - "multi agent"
  - "multiagent"

# Search specifically in titles (optional, comment out if not needed)
title_search: "multi agent"

# ArXiv categories to search in
categories:
  - "cs.AI"    # Artificial Intelligence
  - "cs.MA"    # Multiagent Systems
  - "cs.LG"    # Machine Learning
  - "cs.GT"    # Game Theory

# Date range for papers
start_date: "2024-11-04"  
end_date: "2024-11-11"     # today

# Type of content (optional, comment out if you want all types)
# content_type: "preprint"

# Maximum number of results to return
max_results: 100

summarizer:
  enabled: true  # Set to true to enable summarization
  prompt: |
    Analyze this paper and in no more that 1000 characters explain in simple, everyday language why should someone care about this research? 
    Explain what problem it solves and why it's interesting or important.
    What are the main takeaways? Focus on practical implications and surprising findings.
    Avoid technical jargon and write as if explaining to a curious friend who isn't an expert in the field. Help readers quickly understand if this paper is worth their time.
    Be concise as possible.
    Omit the headers, write everything in one passage.
  max_length: 1000  # Maximum length of summary in characters
  rate_limit_delay: 3  # Delay between API requests in seconds