# ArXiv Query Configuration for Multi-Agent Papers
# Configuration to retrieve recent papers on multi-agent systems in computer science

# General search keywords
keywords:
  - "multi-agent"
  - "multi agent"
  - "multiagent"
  - "multi-agent systems"
  - "multiagent systems"

# Search specifically in titles (optional, comment out if not needed)
# title_search: "multi-agent"

# ArXiv categories to search in
# Using computer science categories relevant to multi-agent systems
categories:
  - "cs.AI"    # Artificial Intelligence
  - "cs.MA"    # Multiagent Systems
  - "cs.LG"    # Machine Learning
  - "cs.GT"    # Game Theory

# Date range for papers
# Setting for the last 7 days from today
start_date: "2023-01-01"  # 7 days ago
end_date: "2024-11-12"     # today

# Type of content (optional, comment out if you want all types)
# content_type: "preprint"

# Maximum number of results to return
max_results: 5

summarizer:
  enabled: true  # Set to true to enable summarization
  prompt: "Summarize this academic paper. Include: main objectives, methodology, key findings, and conclusions. Keep it concise."
  max_length: 300  # Maximum length of summary in characters
  rate_limit_delay: 5  # Delay between API requests in seconds